title: mehran.blog
fa_title: یادداشت‌های مهران شعبانی
author:
  name: "مهران شعبانی"
  email: 'shaban532@gmail.com'
  url: '/author/mehran_shabani'
metadata:
  description: '“همهٔ من” همهٔ من است! من لب به سخن گشوده‌ام؛ قلم به دست گرفته‌ام تا همهٔ خودم را به تحریر در آورم. “همهٔ من” تجلی من است: همان گونه که هستم، همان گونه که می‌اندیشم و همان‌گونه که رفتار می‌کنم.'


description_old: 'یادداشت‌های یک دیوانه، متشکل از مطالبی است که نویسنده در طول سال‌های عمر خویش به تجربه و یا با مطالعه یافته‌است.'

full_description_old: "یادداشت‌های یک دیوانه، متشکل از مطالبی است که نویسنده در طول سال‌های عمر خویش به تجربه و یا با مطالعه یافته‌است.
نویسنده علی رغم اشتهار به دیوانگی تمام سعی خویش را به کار گرفته‌ تا از انتشار مطالب کذب و خلاف واقع بپرهیزد. با این حال مسئولیت تمام عواقب سوء احتمالی ناشی از عمل به مطالب نوشته شده بر عهده خواننده گرامی است."

full_description: "
“همهٔ من” همهٔ من است! سعدی رحمة الله علیه می‌فرماید: تا مرد سخن نگفته باشد عیب و هنرش نهفته باشد و اینک من لب به سخن گشوده‌ام؛ قلم به دست گرفته‌ام تا همهٔ خودم را به تحریر در آورم. “همهٔ من” تجلی من است: همان گونه که هستم، همان گونه که می‌اندیشم و همان‌گونه که رفتار می‌کنم؛ همهٔ عیب و هنر من. “همهٔ من” حتی فراتر از منِ امروز نشان از من سیال در طول زمان دارد: از کجا آمده‌ام و به کجا می‌روم؛ چگونه بوده‌ام و چگونه خواهم شد. پس هر که می‌خواهد مرا بشناسد “همهٔ من” به استقبال نشسته است!
"

taxonomies: [category,tag]
